# fly.toml app configuration file generated for ev-workouts on 2023-09-27T14:13:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ev-workouts"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
